-- Script de criação de dimensão de tempo
GO
DECLARE @DTA_INICIO DATE	= '2005-01-01', 
		@DTA_TERMINO DATE	= '2030-01-01',
		@DTA_REGISTRO DATE  
		
SET LANGUAGE Portuguese

DROP TABLE IF EXISTS #DW_DIM_TEMPO
CREATE TABLE #DW_DIM_TEMPO (
	[COD_DATA]				INT			NOT NULL,	
	[DTA_DIA]				DATE		NOT NULL,
    [NUM_ANO_MES]			AS 			LEFT(CONVERT(VARCHAR, [DTA_DIA], 112), 6),
    [NME_MES]				AS			DATENAME(mm, [DTA_DIA]),
	[NUM_MES]				AS          MONTH([DTA_DIA]),
    [NUM_ANO]				AS			YEAR([DTA_DIA]),
	[DIA_SEMANA]			AS			DATEPART(dw, [DTA_DIA]),
	[NME_DIA_SEMANA]		AS			DATENAME(DW, [DTA_DIA]),
    [NME_DIA_SEMANA_CURTO]	AS			LEFT(DATENAME(DW, [DTA_DIA]), 3),
    [NUM_DIA_MES]			AS			DAY([DTA_DIA]),
    [NUM_DIA_ANO]			AS			DATENAME(DY, [DTA_DIA]),
    [NUM_SEMANA_MES]		AS			DATEPART(WEEK, [DTA_DIA]) - DATEPART(WEEK, DATEADD(MM, DATEDIFF(MM, 0, [DTA_DIA]), 0)) + 1,
    [NUM_SEMANA_ANO]		AS			DATEPART(WK, [DTA_DIA]),
	[NME_MES_CURTO]			AS			LEFT(DATENAME(mm, [DTA_DIA]), 3),
    [NME_MES_ANO]			AS          (CONCAT(LEFT(DATENAME(mm, [DTA_DIA]), 3),'/',YEAR([DTA_DIA]))),
	[NME_MES_ANO_LONGO]		AS			(CONCAT(DATENAME(mm, [DTA_DIA]),'/',YEAR([DTA_DIA]))),
	[NUM_TRIMESTRE]			AS          (DATENAME(QUARTER,TRY_CAST(CONCAT(YEAR([DTA_DIA]),'-',MONTH([DTA_DIA]),'-01') AS [DATE]))),
    [NME_TRIMESTRE]			AS          (CONCAT(DATENAME(QUARTER,TRY_CAST(CONCAT(YEAR([DTA_DIA]),'-',MONTH([DTA_DIA]),'-01') AS [DATE])),'º Trimestre')),
    [NME_TRIMESTRE_ANO]		AS          (CONCAT(DATENAME(QUARTER,TRY_CAST(CONCAT(YEAR([DTA_DIA]),'-',MONTH([DTA_DIA]),'-01') AS [DATE])),'º Trimestre de ',YEAR([DTA_DIA]))),
    [NUM_SEMESTRE]			AS          (CASE WHEN DATEPART(MONTH,MONTH([DTA_DIA]))<(7) THEN (1) ELSE (2) END),
    [NME_SEMESTRE]			AS          (CONCAT(CASE WHEN DATEPART(MONTH,MONTH([DTA_DIA]))<(7) THEN (1) ELSE (2) END,'º Semestre')),
    [NME_SEMESTRE_ANO]		AS          (CONCAT(CASE WHEN DATEPART(MONTH,MONTH([DTA_DIA]))<(7) THEN (1) ELSE (2) END,'º Semestre de ',YEAR([DTA_DIA]))),
    [DTA_INCLUSAO]			DATETIME	CONSTRAINT [DF_DIM_TEMPO_DTA_INCLUSAO] DEFAULT (GETDATE()) NULL,
    [DTA_ATUALIZACAO]		DATETIME	NULL,
    [FLG_ATIVO]				BIT         CONSTRAINT [DF_DIM_TEMPO_FLG_ATIVO] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_DW_DIM_TEMPO] PRIMARY KEY CLUSTERED ([COD_DATA] ASC)
);

SET  @DTA_REGISTRO  = @DTA_INICIO
-- LOOP DE PREENCHIMENTO DE DATAS
WHILE @DTA_REGISTRO   <= @DTA_TERMINO
BEGIN 
	INSERT INTO #DW_DIM_TEMPO
	(
	  COD_DATA
	, DTA_DIA
	)
	VALUES (
		CONVERT(VARCHAR, @DTA_REGISTRO, 112),
		@DTA_REGISTRO
	)

	SET @DTA_REGISTRO = DATEADD(dd, 1, @DTA_REGISTRO)
END 


-- FONTE: ADAPTADO DE https://www.mssqltips.com/sqlservertip/5553/create-an-extended-date-dimension-for-a-sql-server-data-warehouse/